### ISSUE TITLE
what is the service endpoint?

### ISSUE THREAD

**Issue by kanwardeepika91** [onlyutkarsh/gitlab-integration#11]

**Comment by onlyutkarsh** [comment]
https://docs.microsoft.com/en-us/azure/devops/pipelines/library/service-endpoints?view=azure-devops

**Comment by himanshush13** [comment]
@onlyutkarsh , We have a private Gitlab, while creating a service connection in AZURE, it is giving an error while verifying the PAT, Error Message: **'Error while copying content to a stream.'**
Also, for gitlab there is no other connection options.
