### ISSUE TITLE
Cannot load more projects from gitlab

### ISSUE THREAD

**Issue by taivt0109** [onlyutkarsh/gitlab-integration#16]
My Gitlab account has more than 20 projects. But when I add an artifact it loads 20 projects only
![image](https://user-images.githubusercontent.com/8913872/71365552-f65e7700-25d1-11ea-9760-2146ba96cab8.png)
![image](https://user-images.githubusercontent.com/8913872/71365656-40475d00-25d2-11ea-9740-cdcc562dd9e7.png)

**Comment by onlyutkarsh** [comment]
Thanks - Agreed this is an issue and seems to be duplicate of #1 - I will need some spare time to work on this.
