### ISSUE TITLE
Download gitlab repo not working while selecting specific branch option

### ISSUE THREAD

**Issue by SwethaJagadeesh** [onlyutkarsh/gitlab-integration#17]
![image](https://user-images.githubusercontent.com/12410762/71565967-59378e80-2a68-11ea-8042-aa20f91e177c.png)
![image](https://user-images.githubusercontent.com/12410762/71565993-a1ef4780-2a68-11ea-8688-111772eb32bb.png)

**Comment by EwneoN** [comment]
We are also experiencing this issue in our integration

**Comment by onlyutkarsh** [comment]
Hi Guys, Thanks @SwethaJagadeesh for the PR. Appreciate it. @EwneoN Sorry, just back from holiday and bit busy catching up with office work. Will try to pick this up over the weekend.

**Comment by onlyutkarsh** [comment]
@SwethaJagadeesh and @EwneoN - this should be fixed in the latest version - ensure task version is `v1.0.9`

![image](https://user-images.githubusercontent.com/2685029/71930443-90f2b480-3193-11ea-9204-4a0ae2e918b2.png)

**Comment by EwneoN** [comment]
@onlyutkarsh Thanks heaps for fixing this so fast 😄 I was meant to thank you ages ago but it fell off my list.
