### ISSUE TITLE
Project Owner

### ISSUE THREAD

**Issue by josempaguiar** [onlyutkarsh/gitlab-integration#2]
The plugin should fetch all the repositories that I can work and not only the projects that I'm the owner.
Currently, the endpoint is [https://gitlab.com/api/v4/projects?owned=true](https://gitlab.com/api/v4/projects?owned=true) and should be 
[https://gitlab.com/api/v4/projects?membership=true](https://gitlab.com/api/v4/projects?membership=true)

**Comment by onlyutkarsh** [comment]
hey @josempaguiar Makes sense. I can not remember why I went with the `owned` project only. I will see if I can fix this during the upcoming holiday season :-)

**Comment by onlyutkarsh** [comment]
@josempaguiar Sorry this took so long (was super busy with day job). I have changed the endpoint to fetch based on membership now. Hope it will solve the issue for you. Thanks.

**Comment by pesimeao** [comment]
Great @onlyutkarsh ! Thanks! ;)
