### ISSUE TITLE
self hosted URL assumptions

### ISSUE THREAD

**Issue by mfkl** [onlyutkarsh/gitlab-integration#3]
Hello,

Thanks for this extension, I'm in the process of setting it up.

This line assumes things about the URL that is causing problems for me https://github.com/onlyutkarsh/gitlab-integration/blob/c4f68949e0c751ba83a56488dd2838c444b3e453/vss-extension.json#L96

As you can see in those screenshots:
![](https://i.imgur.com/xNVDRfi.png)

This hack makes it work, but probably will be an issue for the next steps.
![](https://i.imgur.com/OfDzhmH.png)

**Comment by onlyutkarsh** [comment]
Hey @mfkl If you are looking to configure the endpoint just to access one single project, that will not work. What happens if you configure Server URL as just `https://code.videolan.org` and username as just `mfkl` with the token? As you can see from the first error, the `/api/v4` is always applied.

**Comment by mfkl** [comment]
> What happens if you configure Server URL as just https://code.videolan.org and username as just mfkl with the token?

The final URL becomes `https://code.videolan.org/api/v4/` which returns `HTTP 404` because the project ID is not specified.

**Comment by onlyutkarsh** [comment]
> > What happens if you configure Server URL as just https://code.videolan.org and username as just mfkl with the token?
> 
> The final URL becomes `https://code.videolan.org/api/v4/` which returns `HTTP 404` because the project ID is not specified.

When you are creating the service connection I use https://code.videolan.org/api/v4/users?username=mfkl to see if I can get the user information. This is just to validate the token you have put in. I do not query for projects there. It should not return 404?

**Comment by mfkl** [comment]
Yes that seems to work, thanks!
